
export const LAST_MPS_INPUT_DATA = 'LAST_MPS_INPUT_DATA-';

export const MPS_VERIF_SS_PREFIX = 'MPS-VERIF-RES-'
export const MPS_DATA_SS_PREFIX = 'MPS-DATA-'


export const SOLVE_LP_DATA_PREFIX = 'LP-DATA-'
export const SOLVE_LP_SOLUTION_ERROR_DATA_PREFIX = 'LP-SOLUTION_ERROR-'
export const SOLVE_LP_SOLUTION_BASIC_SIMPLEX_PREFIX = 'LP-BS-SOLUTION-'
export const SOLVE_LP_SOLUTION_TWO_PHASE_SIMPLEX_PREFIX = 'LP-TP-SOLUTION-'